type PostPageInfo {
  startCursor: DateTime
  endCursor: DateTime
  hasNextPage: Boolean
  hasPreviousPage: Boolean
}

type PostEdge {
  node: Post
  cursor: String
}

type PostsConnection {
  totalCount: Int
  edges: [PostEdge]
  pageInfo: PostPageInfo
}

type Query {
  posts(boardId: String!, cursor: DateTime, offset: Int): PostsConnection
}
