type Post {
  id: ID!
  board: Board!
  title: String!
  content: String!
  commentsCount: Int!
  likesCount: Int!
  createdAt: DateTime
  updatedAt: DateTime
}

type Query {
  post(id: String): Post
}
