type Post {
  id: ID!
  board: Board!
  user: User!
  title: String!
  content: String!
  commentsCount: Int!
  likesCount: Int!
  viewsCount: Int!
  createdAt: DateTime
  updatedAt: DateTime
  comments(cursor: DateTime, offset: Int): CommentsConnection
}

type Query {
  post(id: String): Post
}
