type CommentPageInfo {
  startCursor: DateTime
  endCursor: DateTime
  hasNextPage: Boolean
  hasPreviousPage: Boolean
}

type CommentEdge {
  node: Comment
  cursor: String
}

type CommentsConnection {
  totalCount: Int
  edges: [CommentEdge]
  pageInfo: CommentPageInfo
}
